# Generated by Django 4.0.3 on 2022-06-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='data',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
