# Generated by Django 4.0.3 on 2022-06-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_api', '0004_alter_testmodel_data'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='testmodel',
        #     name='data',
        #     field=models.CharField(max_length=16382, null=True),
        # ),
    ]
