# Generated by Django 4.0.3 on 2022-03-08 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardstats',
            name='frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_stats_frame_records', to='stats_api.frame'),
        ),
        migrations.AlterField(
            model_name='standardstats',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_stats_player_records', to='stats_api.player'),
        ),
        migrations.CreateModel(
            name='ShootingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=100)),
                ('games_starts', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('xg', models.FloatField()),
                ('xa', models.FloatField()),
                ('frame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shooting_stats_frame_records', to='stats_api.frame')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shooting_stats_player_records', to='stats_api.player')),
            ],
        ),
    ]
