# Generated by Django 4.0.3 on 2022-03-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api', '0003_column_columntype_frametype_record_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frame',
            old_name='records_added',
            new_name='cols_added',
        ),
    ]
