# Generated by Django 4.0.3 on 2022-06-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api', '0006_customcolumntype_customframe_customplayer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomColumnDef',
        ),
    ]
