# Generated by Django 4.0.3 on 2022-06-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api', '0007_alter_player_player_id_delete_customcolumndef'),
    ]

    operations = [
    ]
