# Generated by Django 4.0.3 on 2022-06-30 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tables', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcolumn',
            name='expression',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='custom_tables.expression'),
        ),
    ]
