# Generated by Django 4.0.3 on 2022-07-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tables', '0003_alter_customcolumn_expression'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcolumn',
            name='custom_table',
        ),
        migrations.AddField(
            model_name='customcolumn',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
